Implemented Easy AI into offline play. Passing moves requires update.
ERROR: When AI makes a move, gamestate changes current player but does not change a)banner colour, b)piece control.